import json
from pathlib import Path

from ouroboros.diloco.kaggle_dispatch import (
    KAGGLE_ACCELERATOR_T4,
    build_kaggle_kernel_metadata,
    build_worker_dispatch_cell,
    stage_local_kaggle_kernel,
)


def test_metadata_pins_t4_accelerator_and_cache_dataset():
    metadata = build_kaggle_kernel_metadata(slug="weirdrunner/kaggle-utils", notebook_filename="kaggle-utils.ipynb")
    assert metadata["accelerator"] == KAGGLE_ACCELERATOR_T4
    assert metadata["enable_gpu"] is True
    assert "weirdrunner007/ouroboros-cache" in metadata["dataset_sources"]


def test_dispatch_cell_injects_worker_env():
    cell = build_worker_dispatch_cell("b", {"WORKER_ID": "B", "HF_TOKEN": "x"})
    source = "".join(cell["source"])
    assert "AUTO-GENERATED BY DILOCO COORDINATOR" in source
    assert "Bound notebook to DiLoCo worker B" in source


def test_stage_local_kernel_writes_metadata_and_inserts_cell(tmp_path: Path):
    nb = tmp_path / "kaggle-utils.ipynb"
    nb.write_text(json.dumps({"cells": [{"cell_type": "markdown", "metadata": {}, "source": ["# x"]}], "metadata": {}, "nbformat": 4, "nbformat_minor": 5}), encoding="utf-8")
    out_dir = tmp_path / "stage"
    staged = stage_local_kaggle_kernel(nb, "weirdrunner/kaggle-utils", out_dir, worker_id="A")
    assert staged.exists()
    staged_nb = json.loads(staged.read_text(encoding="utf-8"))
    assert staged_nb["cells"][1]["metadata"]["tags"] == ["diloco-dispatch"]
    metadata = json.loads((out_dir / "kernel-metadata.json").read_text(encoding="utf-8"))
    assert metadata["accelerator"] == "NvidiaTeslaT4"
