"""Kaggle dispatch module for DiLoCo workers.

This module hides notebook staging, runtime-env injection, accelerator metadata,
and CLI outcome classification behind a small interface.
"""

from __future__ import annotations

import base64
import json
import os
import shutil
import subprocess
import tempfile
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Mapping, Optional

from .protocol import WORKER_IDS

KAGGLE_ACCELERATOR_T4 = "NvidiaTeslaT4"


@dataclass(frozen=True)
class DispatchRequest:
    worker_id: str
    username: str
    key: str
    slug: str
    notebook_path: Path
    runtime_env: Mapping[str, str] = field(default_factory=dict)
    accelerator: str = KAGGLE_ACCELERATOR_T4


@dataclass(frozen=True)
class DispatchResult:
    worker_id: str
    outcome: str
    stdout: str = ""
    stderr: str = ""
    kernel_version: Optional[str] = None

    @property
    def ok(self) -> bool:
        return self.outcome in {"success", "triggered"}


def encode_runtime_env_payload(runtime_env: Mapping[str, str]) -> str:
    payload = json.dumps(dict(runtime_env), sort_keys=True, separators=(",", ":")).encode("utf-8")
    return base64.b64encode(zlib.compress(payload, level=9)).decode("ascii")


def build_kaggle_kernel_metadata(*, slug: str, notebook_filename: str, accelerator: str = KAGGLE_ACCELERATOR_T4) -> Dict[str, object]:
    title = slug.split("/", 1)[-1]
    return {
        "id": slug,
        "title": title,
        "code_file": notebook_filename,
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": True,
        "accelerator": accelerator,
        "enable_tpu": False,
        "enable_internet": True,
        "dataset_sources": ["weirdrunner007/ouroboros-cache"],
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
        "keywords": [],
    }


def build_worker_dispatch_cell(worker_id: str, runtime_env: Optional[Mapping[str, str]] = None) -> Dict[str, object]:
    wid = str(worker_id).strip().upper()
    if wid not in WORKER_IDS:
        raise ValueError(f"Invalid worker id for notebook dispatch: {worker_id!r}")
    default_env = {
        "DILOCO_WORKER_ID": wid,
        "OUROBOROS_DILOCO_WORKER_ID": wid,
        "WORKER_ID": wid,
        "OUROBOROS_AUTO_TRIGGERED": "1",
    }
    payload = encode_runtime_env_payload(runtime_env or default_env)
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": "diloco-dispatch-worker-id",
        "metadata": {"tags": ["diloco-dispatch"]},
        "outputs": [],
        "source": [
            "# AUTO-GENERATED BY DILOCO COORDINATOR. DO NOT EDIT IN REPO.\n",
            "import base64\n",
            "import json\n",
            "import os\n",
            "import zlib\n",
            f"_DISPATCH_PAYLOAD = {json.dumps(payload)}\n",
            "_DISPATCH_ENV = json.loads(zlib.decompress(base64.b64decode(_DISPATCH_PAYLOAD)).decode('utf-8'))\n",
            "for _dispatch_key, _dispatch_value in _DISPATCH_ENV.items():\n",
            "    if _dispatch_value is None:\n",
            "        continue\n",
            "    os.environ[str(_dispatch_key)] = str(_dispatch_value)\n",
            "del _DISPATCH_ENV, _DISPATCH_PAYLOAD\n",
            f"print('[dispatch] Bound notebook to DiLoCo worker {wid}')\n",
        ],
    }


def stage_local_kaggle_kernel(
    notebook_path: Path,
    slug: str,
    staging_dir: Path,
    *,
    worker_id: Optional[str] = None,
    runtime_env: Optional[Mapping[str, str]] = None,
    accelerator: str = KAGGLE_ACCELERATOR_T4,
) -> Path:
    if not notebook_path.exists():
        raise FileNotFoundError(
            f"Notebook source not found at {notebook_path}. Auto-trigger requires a local kaggle-utils.ipynb checkout."
        )
    staging_dir.mkdir(parents=True, exist_ok=True)
    staged_notebook = staging_dir / notebook_path.name
    shutil.copy2(notebook_path, staged_notebook)

    if worker_id:
        notebook = json.loads(staged_notebook.read_text(encoding="utf-8"))
        cells = notebook.get("cells")
        if not isinstance(cells, list):
            raise ValueError("Kaggle notebook JSON is missing a valid 'cells' list")
        dispatch_cell = build_worker_dispatch_cell(worker_id, runtime_env=runtime_env)
        replaced = False
        for idx, cell in enumerate(cells):
            if not isinstance(cell, dict):
                continue
            source = "".join(cell.get("source", []))
            tags = cell.get("metadata", {}).get("tags", [])
            if "AUTO-GENERATED BY DILOCO COORDINATOR" in source or "diloco-dispatch" in tags:
                cells[idx] = dispatch_cell
                replaced = True
                break
        if not replaced:
            insert_at = 1 if cells and isinstance(cells[0], dict) and cells[0].get("cell_type") == "markdown" else 0
            cells.insert(insert_at, dispatch_cell)
        staged_notebook.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    metadata_path = staging_dir / "kernel-metadata.json"
    metadata_path.write_text(
        json.dumps(
            build_kaggle_kernel_metadata(slug=slug, notebook_filename=staged_notebook.name, accelerator=accelerator),
            indent=2,
        ),
        encoding="utf-8",
    )
    return staged_notebook


class KaggleCliDispatcher:
    """Production adapter using `kaggle kernels push`."""

    def dispatch(self, request: DispatchRequest) -> DispatchResult:
        if not request.username or not request.key:
            return DispatchResult(request.worker_id, "missing_credentials")
        env = os.environ.copy()
        env["KAGGLE_USERNAME"] = request.username
        env["KAGGLE_KEY"] = request.key
        env.pop("KAGGLE_CONFIG_DIR", None)
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                tmp_path = Path(tmpdir)
                stage_local_kaggle_kernel(
                    request.notebook_path,
                    request.slug,
                    tmp_path,
                    worker_id=request.worker_id,
                    runtime_env=request.runtime_env,
                    accelerator=request.accelerator,
                )
                push = subprocess.run(
                    ["kaggle", "kernels", "push", "-p", str(tmp_path), "--accelerator", request.accelerator],
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=120,
                )
        except subprocess.TimeoutExpired as exc:
            return DispatchResult(request.worker_id, "failed", stderr=str(exc))
        except FileNotFoundError as exc:
            return DispatchResult(request.worker_id, "failed", stderr=str(exc))
        except Exception as exc:  # noqa: BLE001 - dispatcher returns structured failure
            return DispatchResult(request.worker_id, "failed", stderr=str(exc))

        if push.returncode != 0:
            stderr = (push.stderr or push.stdout or "").strip()
            lowered = stderr.lower()
            if "quota" in lowered or "exceeded" in lowered:
                return DispatchResult(request.worker_id, "quota_exhausted", stdout=push.stdout, stderr=push.stderr)
            return DispatchResult(request.worker_id, "failed", stdout=push.stdout, stderr=push.stderr)
        return DispatchResult(request.worker_id, "success", stdout=push.stdout, stderr=push.stderr)


class FakeDispatcher:
    """Test adapter for the Kaggle dispatch seam."""

    def __init__(self, outcomes: Optional[Mapping[str, str]] = None) -> None:
        self.outcomes = dict(outcomes or {})
        self.requests: list[DispatchRequest] = []

    def dispatch(self, request: DispatchRequest) -> DispatchResult:
        self.requests.append(request)
        return DispatchResult(request.worker_id, self.outcomes.get(request.worker_id, "success"))


def trigger_single_worker(
    worker_id: str,
    username: str,
    key: str,
    slug: str,
    notebook_path: Path,
    *,
    injected_env: Optional[Mapping[str, str]] = None,
) -> bool:
    result = KaggleCliDispatcher().dispatch(
        DispatchRequest(
            worker_id=str(worker_id).strip().upper(),
            username=username,
            key=key,
            slug=slug,
            notebook_path=notebook_path,
            runtime_env=injected_env or {},
        )
    )
    if result.ok:
        out = (result.stdout or result.stderr or "").strip()
        print(f"[coordinator] Triggered Worker {worker_id}: {slug} ({out})")
        return True
    err = (result.stderr or result.stdout or result.outcome).strip()
    print(f"[coordinator] WARNING: kernels push failed for Worker {worker_id} ({slug}): {err}")
    return False
